export const FETCHING_ALL_GIFS = "FETCHING_ALL_GIFS";
export const FETCHING_GIF_START = "FETCHING_GIF_START";
export const FETCHING_GIF_END = "FETCHING_GIF_END";
export const FETCHING_GIF_FAIL = "FETCHING_GID_FAIL";
